export const jobs = [
  {
    id: 1,
    title: "Senior Frontend Engineer",
    company: "TechCorp",
    location: "San Francisco, CA",
    type: "Full-time",
    category: "Engineering",
    salary: "$140k - $180k",
    postedAt: "2 days ago",
    description: "We are looking for an experienced Frontend Engineer to join our team...",
  },
  {
    id: 2,
    title: "Product Designer",
    company: "DesignStudio",
    location: "Remote",
    type: "Contract",
    category: "Design",
    salary: "$80k - $120k",
    postedAt: "1 week ago",
    description: "Join our creative team to design beautiful and intuitive user interfaces...",
  },
  {
    id: 3,
    title: "Backend Developer",
    company: "DataSystems",
    location: "New York, NY",
    type: "Full-time",
    category: "Engineering",
    salary: "$130k - $170k",
    postedAt: "3 days ago",
    description: "Seeking a Backend Developer with experience in Node.js and Python...",
  },
  {
    id: 4,
    title: "Marketing Manager",
    company: "GrowthHacker",
    location: "Austin, TX",
    type: "Full-time",
    category: "Marketing",
    salary: "$90k - $130k",
    postedAt: "5 days ago",
    description: "Lead our marketing initiatives and drive growth for our new product line...",
  },
  {
    id: 5,
    title: "Customer Support Specialist",
    company: "HelpDesk",
    location: "Remote",
    type: "Part-time",
    category: "Support",
    salary: "$20/hr",
    postedAt: "1 day ago",
    description: "Provide excellent support to our customers via chat and email...",
  },
  {
    id: 6,
    title: "Data Scientist",
    company: "AI Solutions",
    location: "Boston, MA",
    type: "Full-time",
    category: "Data Science",
    salary: "$150k - $200k",
    postedAt: "1 week ago",
    description: "Analyze complex datasets to derive actionable insights...",
  },
];
